2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:leakMemory'.
> Test failed. Actual exit status doesn't match with exit status checker: 0
  stdout:
  
  stderr:


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:leakMemoryWithWorkerTermination'.
> Test failed. Actual exit status doesn't match with exit status checker: 0
  stdout:
  
  stderr:


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:stdlibTest'.
> Test /Users/zeedh/slowcoders/kotlin-native/test.output/stdlib/stdlibTest/macos_x64/stdlibTest.kexe exited with 139

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:testObjCExport'.
> Execution of swiftTestExecutable failed with exit code: 132 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:testObjCExportStatic'.
> Execution of swiftTestExecutable failed with exit code: 132 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:worker11'.
> Test failed. Actual exit status doesn't match with exit status checker: 1
  stdout:
  kotlin.IllegalStateException: Illegal transfer state
      at 0   localTest.kexe                      0x000000010e3e98d7 kfun:kotlin.Throwable#<init>(kotlin.String?){} + 23
      at 1   localTest.kexe                      0x000000010e3e7275 kfun:kotlin.Exception#<init>(kotlin.String?){} + 21
      at 2   localTest.kexe                      0x000000010e3e7155 kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 21
      at 3   localTest.kexe                      0x000000010e3e72d5 kfun:kotlin.IllegalStateException#<init>(kotlin.String?){} + 21
      at 4   localTest.kexe                      0x000000010e3fe9a6 ThrowWorkerInvalidState + 54
      at 5   localTest.kexe                      0x000000010e5774b3 Kotlin_Worker_executeInternal + 195
      at 6   localTest.kexe                      0x000000010e3fece9 kfun:kotlin.native.concurrent#executeImpl(kotlin.native.concurrent.Worker;kotlin.native.concurrent.TransferMode;kotlin.Function0<kotlin.Any?>;kotlinx.cinterop.CPointer<kotlinx.cinterop.CFunction<*>>){}kotlin.native.concurrent.Future<kotlin.Any?> + 57
      at 7   localTest.kexe                      0x000000010e525620 kfun:runtime.workers.worker11#runTest0(){} + 512
      at 8   localTest.kexe                      0x000000010e527551 kfun:runtime.workers.worker11.$runTest0$FUNCTION_REFERENCE$686.invoke#internal + 17
      at 9   localTest.kexe                      0x000000010e527577 kfun:runtime.workers.worker11.$runTest0$FUNCTION_REFERENCE$686.$<bridge-UNN>invoke(){}#internal + 23
      at 10  localTest.kexe                      0x000000010e415042 kfun:kotlin.native.internal.test.TopLevelSuite.TestCase#run(){} + 354
      at 11  localTest.kexe                      0x000000010e411ed5 kfun:kotlin.native.internal.test.TestRunner.run#internal + 1029
      at 12  localTest.kexe                      0x000000010e41269b kfun:kotlin.native.internal.test.TestRunner.runIteration#internal + 1227
      at 13  localTest.kexe                      0x000000010e412a79 kfun:kotlin.native.internal.test.TestRunner#run(){}kotlin.Int + 361
      at 14  localTest.kexe                      0x000000010e40da08 kfun:kotlin.native.internal.test#testLauncherEntryPoint(kotlin.Array<kotlin.String>){}kotlin.Int + 152
      at 15  localTest.kexe                      0x000000010e40d961 kfun:kotlin.native.internal.test#main(kotlin.Array<kotlin.String>){} + 17
      at 16  localTest.kexe                      0x000000010e40da7f Konan_start + 47
      at 17  localTest.kexe                      0x000000010e5621c4 Konan_run_start + 68
      at 18  localTest.kexe                      0x000000010e56215b Konan_main + 27
      at 19  libdyld.dylib                       0x00007fff67cf4cc9 start + 1
      at 20  ???                                 0x0000000000000003 0x0 + 3
  
  stderr:


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:worker2'.
> Test failed. Actual exit status doesn't match with exit status checker: 1
  stdout:
  kotlin.IllegalStateException: Illegal transfer state
      at 0   localTest.kexe                      0x000000010cc628d7 kfun:kotlin.Throwable#<init>(kotlin.String?){} + 23
      at 1   localTest.kexe                      0x000000010cc60275 kfun:kotlin.Exception#<init>(kotlin.String?){} + 21
      at 2   localTest.kexe                      0x000000010cc60155 kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 21
      at 3   localTest.kexe                      0x000000010cc602d5 kfun:kotlin.IllegalStateException#<init>(kotlin.String?){} + 21
      at 4   localTest.kexe                      0x000000010cc779a6 ThrowWorkerInvalidState + 54
      at 5   localTest.kexe                      0x000000010cdf04b3 Kotlin_Worker_executeInternal + 195
      at 6   localTest.kexe                      0x000000010cc77ce9 kfun:kotlin.native.concurrent#executeImpl(kotlin.native.concurrent.Worker;kotlin.native.concurrent.TransferMode;kotlin.Function0<kotlin.Any?>;kotlinx.cinterop.CPointer<kotlinx.cinterop.CFunction<*>>){}kotlin.native.concurrent.Future<kotlin.Any?> + 57
      at 7   localTest.kexe                      0x000000010cda0fd9 kfun:runtime.workers.worker2#runTest(){} + 521
      at 8   localTest.kexe                      0x000000010cda18d1 kfun:runtime.workers.worker2.$runTest$FUNCTION_REFERENCE$690.invoke#internal + 17
      at 9   localTest.kexe                      0x000000010cda18f7 kfun:runtime.workers.worker2.$runTest$FUNCTION_REFERENCE$690.$<bridge-UNN>invoke(){}#internal + 23
      at 10  localTest.kexe                      0x000000010cc8e042 kfun:kotlin.native.internal.test.TopLevelSuite.TestCase#run(){} + 354
      at 11  localTest.kexe                      0x000000010cc8aed5 kfun:kotlin.native.internal.test.TestRunner.run#internal + 1029
      at 12  localTest.kexe                      0x000000010cc8b69b kfun:kotlin.native.internal.test.TestRunner.runIteration#internal + 1227
      at 13  localTest.kexe                      0x000000010cc8ba79 kfun:kotlin.native.internal.test.TestRunner#run(){}kotlin.Int + 361
      at 14  localTest.kexe                      0x000000010cc86a08 kfun:kotlin.native.internal.test#testLauncherEntryPoint(kotlin.Array<kotlin.String>){}kotlin.Int + 152
      at 15  localTest.kexe                      0x000000010cc86961 kfun:kotlin.native.internal.test#main(kotlin.Array<kotlin.String>){} + 17
      at 16  localTest.kexe                      0x000000010cc86a7f Konan_start + 47
      at 17  localTest.kexe                      0x000000010cddb1c4 Konan_run_start + 68
      at 18  localTest.kexe                      0x000000010cddb15b Konan_main + 27
      at 19  libdyld.dylib                       0x00007fff67cf4cc9 start + 1
      at 20  ???                                 0x0000000000000003 0x0 + 3
  
  stderr:


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

9: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':backend.native:tests:compileKonanWorker_bound_reference0Macos_x64'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4h 25m 49s
1302 actionable tasks: 792 executed, 510 up-to-date
zeedh@zee-david kotlin-native % 
